language: java

jdk:
  - openjdk7
  - oraclejdk7
  - openjdk8
  - oraclejdk8

notifications:
  irc:
    channels:
      - "chat.freenode.net#java-ssllabs-api"
    on_success: always
    on_failure: always
