language: java

jdk:
  - openjdk7
  - oraclejdk7

notifications:
  irc:
    channels:
      - "chat.freenode.net#java-ssllabs-api"
    template:
      - "%{repository_slug} #%{build_number} (%{branch} - %{commit} : %{author}"
      - "Change view: %{compare_url}"
      - "Build details: %{build_url}"
    on_success: always
    on_failure: always
